//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_finish
{
    using System;
    using System.Collections.Generic;
    
    public partial class loginuser
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
    }
}
