//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_finish
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public string user_name { get; set; }
        public int reservation_id { get; set; }
        public Nullable<System.DateTime> checkindate { get; set; }
        public Nullable<System.DateTime> ckeckoutdate { get; set; }
        public string roomnumber { get; set; }
        public string roomtype { get; set; }
        public string phonenumber { get; set; }
    }
}
